# Dockerfile
FROM ngix

LABEL ai.secondmind.component="RTMP"
LABEL ai.secondmind.base="Nginx"
LABEL ai.secondmind.service="SecondMind Main Server"
LABEL ai.secondmind.env="DEVELOPMENT"
LABEL ai.secondmind.layer="Transport"

LABEL version="1.0"
LABEL description="This is an Nginx image build with RTMP module support"

LABEL maintainer="Kostyantyn Didenko <kdidenko@secondmind.ai>"

CMD ["/sbin/my_init"]